import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

// Re-export the better-auth tables (user/session/account/verification) so that
// both drizzle-kit (migrations) and the better-auth drizzle adapter can see
// them. `auth.schema.ts` is regenerated by `pnpm auth:schema`.
export * from './auth.schema';

export const task = sqliteTable('task', {
	id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
	title: text('title').notNull(),
	priority: integer('priority').notNull().default(1)
});

